'use client';
import Image from 'next/image';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useState } from 'react';
import { LanguageSwitcher } from './LanguageSwitcher';
import type { Locale } from '../../lib/i18n';
type NavItem={href:string;label:string;key:string;active:boolean};
export function Header({locale,nav,common}:{locale:Locale;nav:Record<string,string>;common:{language:string;menuOpen:string;menuClose:string;logoAlt:string}}){const [open,setOpen]=useState(false);const pathname=usePathname();const currentPath=pathname.replace(new RegExp(`^/${locale}`),'')||'';const items:NavItem[]=[{key:'home',href:'',label:nav.home,active:currentPath===''},{key:'about',href:'/qui-sommes-nous',label:nav.about,active:currentPath==='/qui-sommes-nous'},{key:'services',href:'/services',label:nav.services,active:currentPath==='/services'},{key:'directory',href:'/annuaire',label:nav.directory,active:currentPath==='/annuaire'},{key:'join',href:'/contact',label:nav.join,active:false},{key:'information',href:'/informations',label:nav.information,active:currentPath==='/informations'},{key:'announcements',href:'/annonces',label:nav.announcements,active:currentPath==='/annonces'},{key:'contact',href:'/contact',label:nav.contact,active:currentPath==='/contact'}];return <header className="sticky top-0 z-50 border-b border-white/10 bg-primary/95 text-white shadow-lg backdrop-blur"><div className="container-shell flex min-h-[76px] items-center justify-between gap-4"><Link href={`/${locale}`} className="focus-ring flex w-[4.5rem] flex-col items-center gap-1 sm:w-auto sm:flex-row sm:gap-3" onClick={()=>setOpen(false)}><Image src="/images/logo-asecam.jpg" width={52} height={52} alt={common.logoAlt} className="h-12 w-12 rounded-full object-cover ring-2 ring-accent-gold/70"/><span className="font-display text-center text-[11px] font-semibold tracking-wide sm:text-left sm:text-sm">ASECAM</span></Link><nav className="hidden items-center gap-4 lg:flex">{items.map(item=><Link key={item.key} href={`/${locale}${item.href}`} aria-current={item.active?'page':undefined} className={`focus-ring text-sm font-medium transition ${item.active?'text-accent-gold':'text-white/85 hover:text-accent-gold'}`}>{item.label}</Link>)}<LanguageSwitcher locale={locale} ariaLabel={common.language}/></nav><div className="flex items-center gap-2 lg:hidden"><LanguageSwitcher locale={locale} ariaLabel={common.language}/><button type="button" aria-label={open?common.menuClose:common.menuOpen} aria-expanded={open} onClick={()=>setOpen(v=>!v)} className="focus-ring rounded-lg border border-white/20 px-3 py-2 text-xl">{open?'×':'☰'}</button></div></div>{open&&<nav className="container-shell border-t border-white/15 py-4 lg:hidden">{items.map(item=><Link key={item.key} href={`/${locale}${item.href}`} aria-current={item.active?'page':undefined} onClick={()=>setOpen(false)} className={`block border-b border-white/10 py-3 text-sm font-medium ${item.active?'font-semibold text-accent-gold':'text-white/90'}`}>{item.label}</Link>)}</nav>}</header>}
